require: rubocop-rspec

AllCops:
  Exclude:
    - spec/**/*

Documentation:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
