language: ruby
rvm:
  - 2.2.2
  - 2.2.4
  - 2.3.1
  - rbx-3.29
addons:
  postgresql: 9.4
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/dblint
before_install:
  - gem install bundler
before_script:
  - createdb dblint
script: bundle exec rake
