language: ruby
rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.3.1
  - rbx-3.20
addons:
  postgresql: 9.4
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/dblint
before_install:
  - gem install bundler
before_script:
  - createdb dblint
script: bundle exec rake
